// This file is auto-generated from 'Springboard Annual Survey.xlsx'

export const TAXONOMIES = {
  "Type of Registration": [
    "Corporation",
    "Event",
    "Network",
    "Organization",
    "Person",
    "Program / Project / Initiative",
  ],
  "Legal Status": [
    "NGO / Non-profit",
    "Private / For-Profit",
    "Public sector",
    "Unclear",
  ],
  "Entity Size (staff)": [
    "1",
    "1001-5000",
    "11-50",
    "2-10",
    "201-500",
    "5001+",
    "501-1000",
    "51-200",
    "No Data",
  ],
  "Entity Type": [
    "Civil Society Organization (Advocacy and public communication/Intermediation and facilitation/Monitoring/Protection/Service delivery/Social cohesion)",
    "Consultancy / Professional Services",
    "Cultural institution (Museum/Art gallery/Music school)",
    "Educational Institution (University / Research Center / College / School / Institute)",
    "Foundation / Grantmaker",
    "Freelance",
    "Government or Public administration (Regional/National/International)",
    "Healthcare Institution",
    "Hub / Co-Working / Lab",
    "Individual Philanthropist",
    "Media / Communication",
    "Medium or Big Corporation",
    "Online Platform",
    "Publishing & Editorial Houses",
    "Retreat Center",
    "Startup / Small business",
    "Think Tank",
  ],
  "Continent": [
    "Africa",
    "Asia",
    "Australia / Oceania",
    "Central & South America",
    "Europe",
    "North America",
  ],
  "Country": [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Côte d’Ivoire",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Republic of the Congo",
    "Romania",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "São Tomé and Príncipe",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
  ],
  "Region": [
    "Bangladesh",
    "Brazil",
    "Central & Eastern Europe",
    "Central Asia",
    "East & South Africa",
    "East Asia",
    "European Mediterranean",
    "Himalayan",
    "India",
    "Latin America",
    "Northern Europe",
    "Oceania",
    "Southeast Asia",
    "US & Canada",
    "WANA (West Asia & North Africa)",
    "West & Central Africa",
    "Western Europe",
  ],
  "Area of Work": [
    "Adviser / Consultant",
    "Advocacy / Public Communication",
    "Coaching / Counseling",
    "Content Design / Production / Curation",
    "Convening / Events",
    "Formal Education / Academia",
    "Grassroots Efforts",
    "Intermediation / Facilitation",
    "Manufacturing Goods",
    "Marketing / Advertising / Creatives",
    "Monitoring",
    "Narrative Change / Storytelling / Journalism",
    "Networks & Partnerships",
    "Philanthropic Efforts",
    "Politics / Public Policies",
    "Prevention / Preventive Education",
    "Research",
    "Service delivery",
    "Social Cohesion / Community Building",
    "Strategy Development / Strategy Implementation",
    "Training / Non-formal Education",
  ],
  "Focus of Work": [
    "Agriculture / Agronomy",
    "Alternative Methodologies",
    "Architectural development",
    "Arts / Culture / Entertainment",
    "Audio / Visual Efforts",
    "Business / Finance / Financial Services",
    "Climate Justice / Action",
    "Democracy / Active Citizenship",
    "Economic Development / Economic Empowerment",
    "Emergency Relief",
    "Environment / Ecology",
    "Fashion / Design",
    "Global Pressing Social Problems / SDG",
    "Human Rights",
    "Individuals' Inner Wellbeing Journey",
    "JEDI (Justice / Equity / Diversity / Inclusion)",
    "Knowledge / Resource Democratization",
    "Law / Legal Aid",
    "Leadership / Capacity Building",
    "Mental Health",
    "Organizational Wellbeing",
    "Peace & Non-Violence Culture / Socio-cultural Transformation",
    "Physical Health",
    "Protection / Safety",
    "Public Affairs",
    "Religious / Faith-based / Spiritual Practices",
    "Resource Mobilization",
    "Schooling / Academic Curricula",
    "Social Entrepreneurship",
    "Social Innovation / Need-Solution Approach",
    "Socio-Emotional Education",
    "Sustainability / Sustainable Development",
    "Systems Change",
    "Technology / Cybersecurity / AI",
    "Trauma-informed Healing / Practices",
    "Truth / Remembering / Reconciliation",
    "Wellbeing Enhancing Practices",
  ],
  "Target Audience": [
    "Artists",
    "Black / People of Color",
    "Businesses / Institutions",
    "Changemakers",
    "Civil Servants",
    "Coaches / Facilitators",
    "Communities",
    "Early age / Children",
    "Economists",
    "Elders",
    "Environmentalists",
    "Farmers",
    "Foundations / Philanthropists",
    "Girls",
    "Governments / Public Institutions",
    "Health Professionals",
    "Indigenous People",
    "Individuals",
    "LGBTQ+",
    "Media Channels",
    "Men",
    "NGOs / Civil Society Organizations",
    "Nature",
    "Parents / Caregivers",
    "Retreat Centers",
    "Schools (Public or Private)",
    "Scientists / Academics",
    "Social Entrepreneurs",
    "Staff / Employees",
    "Storytellers / Journalists",
    "Students",
    "Teachers / Educators",
    "Women",
    "Youth",
  ],
  "Audience Specifics": [
    "Activists",
    "Crime related",
    "Diseased Affected",
    "Domestic Focus",
    "Drug related",
    "Educational Sector",
    "Expatriates",
    "Faith-based Community",
    "Grassroots",
    "Head of Household",
    "Healthcare Sector",
    "Homeless People",
    "Labor Market",
    "Leaders",
    "Legal Sector",
    "Marginalized / Vulnerated",
    "Media Sector",
    "Migrants",
    "Natural World",
    "People with Disabilities",
    "Poverty",
    "Refugees / Displaced People",
    "Rural / Under-Urbanized",
    "Self-employed",
    "Sex Industry",
    "Sexual Abuse Victims",
    "Social Impact Purpose",
    "Soldiers",
    "Territorial / Geographical Interests",
    "War / Conflict-affected Victims",
  ],
  "Community Type & Beneficiaries": [
    "Fellows",
    "Grantees",
    "Individual Members",
    "Organization Members",
    "Students in specific programs",
  ],
  "Specialties": [
    "Burnout & Chronic Stress Recovery",
    "Compassion Fatigue & Moral Injury",
    "Conflict Transformation & Mediation",
    "Cultural & Intergenerational Healing",
    "Ecosystem and Movement Building",
    "Emotional Resilience & Regulation",
    "Family Systems & Relational Work",
    "Grief, Loss & Life Transitions",
    "Group Facilitation & Collective Processes",
    "Identity-Based & Racialized Stress",
    "Leadership Coaching",
    "Organizational Wellbeing & Team Care",
    "Retreat Design & Facilitation",
    "Somatic & Body-Based Healing",
    "Spiritual & Meaning-Centered Support",
    "Trauma-Informed Healing",
    "Youth Wellbeing",
  ],
  "Modalities & Approaches": [
    "Breathwork & Conscious Breathing",
    "Coaching & Integrative Coaching",
    "Cognitive & Behavioral Therapies",
    "Creative & Arts-Based Therapies",
    "Indigenous & Ancestral Practices",
    "Internal Family Systems (IFS)",
    "Mindfulness & Contemplative Practices",
    "Movement & Expressive Therapies",
    "Narrative & Meaning-Centered Approaches",
    "Nature-Based & Ecological Approaches",
    "Nonviolent Communication & Relational Practices",
    "Restorative & Transformative Justice Practices",
    "Somatic & Body-Based Therapies",
    "Spiritual Direction & Accompaniment",
    "Systems & Constellation Work",
    "Trauma-Focused Therapies (EMDR, SE, etc.)",
  ],
  "Language": [
    "Amharic",
    "Arabic",
    "Bengali",
    "English",
    "French",
    "German",
    "Hindi",
    "Japanese",
    "Korean",
    "Mandarin Chinese",
    "Portuguese",
    "Russian",
    "Sign Language (ASL)",
    "Spanish",
    "Swahili",
    "Tagalog (Filipino)",
    "Urdu",
    "Vietnamese",
  ],
  "Resource Type": [
    "Article / Essay",
    "Book / Book Chapter",
    "Case Study / Practice Example",
    "Course / Training",
    "Curriculum / Learning Module",
    "Infographic / Illustration",
    "Podcast / Audio",
    "Policy Brief",
    "Practice / Exercise",
    "Report / White Paper",
    "Research Paper",
    "Toolkit / Guide",
    "Webinar / Talk",
    "Workshop Recording",
  ],
  "Area (Primary wellbeing domain addressed)": [
    "Burnout & Chronic Stress",
    "Care Ethics, Solidarity & Mutual Aid",
    "Climate & Planetary Wellbeing",
    "Collective Care & Community Wellbeing",
    "Compassion Fatigue & Moral Injury",
    "Cultural, Identity & Belonging-Based Healing",
    "Ecological Belonging",
    "Emotional Regulation & Nervous System Health",
    "Grief, Loss & Life Transitions",
    "Individual Wellbeing & Inner Resourcing",
    "Leadership Wellbeing & Capacity Building",
    "Mental and Emotional Health & Resilience",
    "Movement Sustainability & Ecosystem Care",
    "Organizational Wellbeing & Workplace Culture",
    "Rest, Recovery & Regenerative Practices",
    "Somatic & Body-Based Practices",
    "Trauma-Informed & Intergenerational Healing",
    "Youth & Intergenerational Wellbeing",
  ],
  "Topic (Specific lens, population, system, or approach)": [
    "Art, Culture & Storytelling",
    "Cities, Architecture & Spaces of Belonging",
    "Collective & Relational Wellbeing",
    "Development, Global South & Power Dynamics",
    "Food Systems, Land & Regenerative Futures",
    "Governance, Democracy & Polarisation",
    "Intergenerational Memory & Collective Healing",
    "Neuroscience & Trauma Science",
    "Organizational Health",
    "Peacebuilding, Conflict & Reconciliation",
    "Philanthropy, Funding & Care Ethics",
    "Physical Health",
    "Sacred Economies & Business for Good",
    "Social, Racial & Healing Justice",
    "Spirituality, Meaning & Sacred Worldviews",
    "Systems Change & Social Transformation",
    "Technology, AI & Wellbeing",
    "The Interconnectedness of All Life",
  ],
} as const;

export const COUNTRY_TO_REGION: Record<string, string> = {
  "Afghanistan": "Central Asia",
  "Albania": "European Mediterranean",
  "Algeria": "WANA (West Asia & North Africa)",
  "Andorra": "Western Europe",
  "Angola": "West & Central Africa",
  "Antigua and Barbuda": "Latin America",
  "Argentina": "Latin America",
  "Armenia": "WANA (West Asia & North Africa)",
  "Australia": "Oceania",
  "Austria": "Western Europe",
  "Azerbaijan": "WANA (West Asia & North Africa)",
  "Bahamas": "Latin America",
  "Bahrain": "WANA (West Asia & North Africa)",
  "Bangladesh": "Bangladesh",
  "Barbados": "Latin America",
  "Belarus": "Central & Eastern Europe",
  "Belgium": "Western Europe",
  "Belize": "Latin America",
  "Benin": "West & Central Africa",
  "Bhutan": "Himalayan",
  "Bolivia": "Latin America",
  "Bosnia and Herzegovina": "European Mediterranean",
  "Botswana": "East & South Africa",
  "Brazil": "Brazil",
  "Brunei": "Southeast Asia",
  "Bulgaria": "Central & Eastern Europe",
  "Burkina Faso": "West & Central Africa",
  "Burundi": "East & South Africa",
  "Cabo Verde": "West & Central Africa",
  "Cambodia": "Southeast Asia",
  "Cameroon": "West & Central Africa",
  "Canada": "US & Canada",
  "Central African Republic": "West & Central Africa",
  "Chad": "West & Central Africa",
  "Chile": "Latin America",
  "China": "East Asia",
  "Colombia": "Latin America",
  "Comoros": "East & South Africa",
  "Costa Rica": "Latin America",
  "Croatia": "European Mediterranean",
  "Cuba": "Latin America",
  "Cyprus": "WANA (West Asia & North Africa)",
  "Czech Republic": "Central & Eastern Europe",
  "Côte d’Ivoire": "West & Central Africa",
  "Democratic Republic of the Congo": "West & Central Africa",
  "Denmark": "Northern Europe",
  "Djibouti": "East & South Africa",
  "Dominica": "Latin America",
  "Dominican Republic": "Latin America",
  "Ecuador": "Latin America",
  "Egypt": "WANA (West Asia & North Africa)",
  "El Salvador": "Latin America",
  "Equatorial Guinea": "West & Central Africa",
  "Eritrea": "East & South Africa",
  "Estonia": "Northern Europe",
  "Eswatini": "East & South Africa",
  "Ethiopia": "East & South Africa",
  "Fiji": "Oceania",
  "Finland": "Northern Europe",
  "France": "Western Europe",
  "Gabon": "West & Central Africa",
  "Gambia": "West & Central Africa",
  "Georgia": "WANA (West Asia & North Africa)",
  "Germany": "Western Europe",
  "Ghana": "West & Central Africa",
  "Greece": "European Mediterranean",
  "Grenada": "Latin America",
  "Guatemala": "Latin America",
  "Guinea": "West & Central Africa",
  "Guinea-Bissau": "West & Central Africa",
  "Guyana": "Latin America",
  "Haiti": "Latin America",
  "Honduras": "Latin America",
  "Hungary": "Central & Eastern Europe",
  "Iceland": "Northern Europe",
  "India": "India",
  "Indonesia": "Southeast Asia",
  "Iran": "WANA (West Asia & North Africa)",
  "Iraq": "WANA (West Asia & North Africa)",
  "Ireland": "Northern Europe",
  "Israel": "WANA (West Asia & North Africa)",
  "Italy": "European Mediterranean",
  "Jamaica": "Latin America",
  "Japan": "East Asia",
  "Jordan": "WANA (West Asia & North Africa)",
  "Kazakhstan": "Central Asia",
  "Kenya": "East & South Africa",
  "Kiribati": "Oceania",
  "Kuwait": "WANA (West Asia & North Africa)",
  "Kyrgyzstan": "Central Asia",
  "Laos": "Southeast Asia",
  "Latvia": "Northern Europe",
  "Lebanon": "WANA (West Asia & North Africa)",
  "Lesotho": "East & South Africa",
  "Liberia": "West & Central Africa",
  "Libya": "WANA (West Asia & North Africa)",
  "Liechtenstein": "Western Europe",
  "Lithuania": "Northern Europe",
  "Luxembourg": "Western Europe",
  "Madagascar": "East & South Africa",
  "Malawi": "East & South Africa",
  "Malaysia": "Southeast Asia",
  "Maldives": "Southeast Asia",
  "Mali": "West & Central Africa",
  "Malta": "European Mediterranean",
  "Marshall Islands": "Oceania",
  "Mauritania": "West & Central Africa",
  "Mauritius": "East & South Africa",
  "Mexico": "Latin America",
  "Micronesia": "Oceania",
  "Moldova": "Central & Eastern Europe",
  "Monaco": "Western Europe",
  "Mongolia": "East Asia",
  "Montenegro": "European Mediterranean",
  "Morocco": "WANA (West Asia & North Africa)",
  "Mozambique": "East & South Africa",
  "Myanmar": "Southeast Asia",
  "Namibia": "East & South Africa",
  "Nauru": "Oceania",
  "Nepal": "Himalayan",
  "Netherlands": "Western Europe",
  "New Zealand": "Oceania",
  "Nicaragua": "Latin America",
  "Niger": "West & Central Africa",
  "Nigeria": "West & Central Africa",
  "North Korea": "East Asia",
  "North Macedonia": "European Mediterranean",
  "Norway": "Northern Europe",
  "Oman": "WANA (West Asia & North Africa)",
  "Pakistan": "Central Asia",
  "Palau": "Oceania",
  "Panama": "Latin America",
  "Papua New Guinea": "Oceania",
  "Paraguay": "Latin America",
  "Peru": "Latin America",
  "Philippines": "Southeast Asia",
  "Poland": "Central & Eastern Europe",
  "Portugal": "European Mediterranean",
  "Qatar": "WANA (West Asia & North Africa)",
  "Republic of the Congo": "West & Central Africa",
  "Romania": "Central & Eastern Europe",
  "Rwanda": "East & South Africa",
  "Saint Kitts and Nevis": "Latin America",
  "Saint Lucia": "Latin America",
  "Saint Vincent and the Grenadines": "Latin America",
  "Samoa": "Oceania",
  "San Marino": "European Mediterranean",
  "Saudi Arabia": "WANA (West Asia & North Africa)",
  "Senegal": "West & Central Africa",
  "Serbia": "Central & Eastern Europe",
  "Seychelles": "East & South Africa",
  "Sierra Leone": "West & Central Africa",
  "Singapore": "Southeast Asia",
  "Slovakia": "Central & Eastern Europe",
  "Slovenia": "Central & Eastern Europe",
  "Solomon Islands": "Oceania",
  "Somalia": "East & South Africa",
  "South Africa": "East & South Africa",
  "South Korea": "East Asia",
  "South Sudan": "East & South Africa",
  "Spain": "European Mediterranean",
  "Sri Lanka": "Southeast Asia",
  "Sudan": "East & South Africa",
  "Suriname": "Latin America",
  "Sweden": "Northern Europe",
  "Switzerland": "Western Europe",
  "Syria": "WANA (West Asia & North Africa)",
  "São Tomé and Príncipe": "West & Central Africa",
  "Tajikistan": "Central Asia",
  "Tanzania": "East & South Africa",
  "Thailand": "Southeast Asia",
  "Timor-Leste": "Southeast Asia",
  "Togo": "West & Central Africa",
  "Tonga": "Oceania",
  "Trinidad and Tobago": "Latin America",
  "Tunisia": "WANA (West Asia & North Africa)",
  "Turkey": "WANA (West Asia & North Africa)",
  "Turkmenistan": "Central Asia",
  "Tuvalu": "Oceania",
  "Uganda": "East & South Africa",
  "Ukraine": "Central & Eastern Europe",
  "United Arab Emirates": "WANA (West Asia & North Africa)",
  "United Kingdom": "Northern Europe",
  "United States": "US & Canada",
  "Uruguay": "Latin America",
  "Uzbekistan": "Central Asia",
  "Vanuatu": "Oceania",
  "Vatican City": "European Mediterranean",
  "Venezuela": "Latin America",
  "Vietnam": "Southeast Asia",
  "Yemen": "WANA (West Asia & North Africa)",
  "Zambia": "East & South Africa",
  "Zimbabwe": "East & South Africa",
};

export const COUNTRY_TO_CONTINENT: Record<string, string> = {
  "Afghanistan": "Asia",
  "Albania": "Europe",
  "Algeria": "Africa",
  "Andorra": "Europe",
  "Angola": "Africa",
  "Antigua and Barbuda": "Central & South America",
  "Argentina": "Central & South America",
  "Armenia": "Asia",
  "Australia": "Australia / Oceania",
  "Austria": "Europe",
  "Azerbaijan": "Asia",
  "Bahamas": "Central & South America",
  "Bahrain": "Asia",
  "Bangladesh": "Asia",
  "Barbados": "Central & South America",
  "Belarus": "Europe",
  "Belgium": "Europe",
  "Belize": "Central & South America",
  "Benin": "Africa",
  "Bhutan": "Asia",
  "Bolivia": "Central & South America",
  "Bosnia and Herzegovina": "Europe",
  "Botswana": "Africa",
  "Brazil": "Central & South America",
  "Brunei": "Asia",
  "Bulgaria": "Europe",
  "Burkina Faso": "Africa",
  "Burundi": "Africa",
  "Cabo Verde": "Africa",
  "Cambodia": "Asia",
  "Cameroon": "Africa",
  "Canada": "North America",
  "Central African Republic": "Africa",
  "Chad": "Africa",
  "Chile": "Central & South America",
  "China": "Asia",
  "Colombia": "Central & South America",
  "Comoros": "Africa",
  "Costa Rica": "Central & South America",
  "Croatia": "Europe",
  "Cuba": "Central & South America",
  "Cyprus": "Asia",
  "Czech Republic": "Europe",
  "Côte d’Ivoire": "Africa",
  "Democratic Republic of the Congo": "Africa",
  "Denmark": "Europe",
  "Djibouti": "Africa",
  "Dominica": "Central & South America",
  "Dominican Republic": "Central & South America",
  "Ecuador": "Central & South America",
  "Egypt": "Africa",
  "El Salvador": "Central & South America",
  "Equatorial Guinea": "Africa",
  "Eritrea": "Africa",
  "Estonia": "Europe",
  "Eswatini": "Africa",
  "Ethiopia": "Africa",
  "Fiji": "Australia / Oceania",
  "Finland": "Europe",
  "France": "Europe",
  "Gabon": "Africa",
  "Gambia": "Africa",
  "Georgia": "Asia",
  "Germany": "Europe",
  "Ghana": "Africa",
  "Greece": "Europe",
  "Grenada": "Central & South America",
  "Guatemala": "Central & South America",
  "Guinea": "Africa",
  "Guinea-Bissau": "Africa",
  "Guyana": "Central & South America",
  "Haiti": "Central & South America",
  "Honduras": "Central & South America",
  "Hungary": "Europe",
  "Iceland": "Europe",
  "India": "Asia",
  "Indonesia": "Asia",
  "Iran": "Asia",
  "Iraq": "Asia",
  "Ireland": "Europe",
  "Israel": "Asia",
  "Italy": "Europe",
  "Jamaica": "Central & South America",
  "Japan": "Asia",
  "Jordan": "Asia",
  "Kazakhstan": "Asia",
  "Kenya": "Africa",
  "Kiribati": "Australia / Oceania",
  "Kuwait": "Asia",
  "Kyrgyzstan": "Asia",
  "Laos": "Asia",
  "Latvia": "Europe",
  "Lebanon": "Asia",
  "Lesotho": "Africa",
  "Liberia": "Africa",
  "Libya": "Africa",
  "Liechtenstein": "Europe",
  "Lithuania": "Europe",
  "Luxembourg": "Europe",
  "Madagascar": "Africa",
  "Malawi": "Africa",
  "Malaysia": "Asia",
  "Maldives": "Asia",
  "Mali": "Africa",
  "Malta": "Europe",
  "Marshall Islands": "Australia / Oceania",
  "Mauritania": "Africa",
  "Mauritius": "Africa",
  "Mexico": "North America",
  "Micronesia": "Australia / Oceania",
  "Moldova": "Europe",
  "Monaco": "Europe",
  "Mongolia": "Asia",
  "Montenegro": "Europe",
  "Morocco": "Africa",
  "Mozambique": "Africa",
  "Myanmar": "Asia",
  "Namibia": "Africa",
  "Nauru": "Australia / Oceania",
  "Nepal": "Asia",
  "Netherlands": "Europe",
  "New Zealand": "Australia / Oceania",
  "Nicaragua": "Central & South America",
  "Niger": "Africa",
  "Nigeria": "Africa",
  "North Korea": "Asia",
  "North Macedonia": "Europe",
  "Norway": "Europe",
  "Oman": "Asia",
  "Pakistan": "Asia",
  "Palau": "Australia / Oceania",
  "Panama": "Central & South America",
  "Papua New Guinea": "Australia / Oceania",
  "Paraguay": "Central & South America",
  "Peru": "Central & South America",
  "Philippines": "Asia",
  "Poland": "Europe",
  "Portugal": "Europe",
  "Qatar": "Asia",
  "Republic of the Congo": "Africa",
  "Romania": "Europe",
  "Rwanda": "Africa",
  "Saint Kitts and Nevis": "Central & South America",
  "Saint Lucia": "Central & South America",
  "Saint Vincent and the Grenadines": "Central & South America",
  "Samoa": "Australia / Oceania",
  "San Marino": "Europe",
  "Saudi Arabia": "Asia",
  "Senegal": "Africa",
  "Serbia": "Europe",
  "Seychelles": "Africa",
  "Sierra Leone": "Africa",
  "Singapore": "Asia",
  "Slovakia": "Europe",
  "Slovenia": "Europe",
  "Solomon Islands": "Australia / Oceania",
  "Somalia": "Africa",
  "South Africa": "Africa",
  "South Korea": "Asia",
  "South Sudan": "Africa",
  "Spain": "Europe",
  "Sri Lanka": "Asia",
  "Sudan": "Africa",
  "Suriname": "Central & South America",
  "Sweden": "Europe",
  "Switzerland": "Europe",
  "Syria": "Asia",
  "São Tomé and Príncipe": "Africa",
  "Tajikistan": "Asia",
  "Tanzania": "Africa",
  "Thailand": "Asia",
  "Timor-Leste": "Asia",
  "Togo": "Africa",
  "Tonga": "Australia / Oceania",
  "Trinidad and Tobago": "Central & South America",
  "Tunisia": "Africa",
  "Turkey": "Asia",
  "Turkmenistan": "Asia",
  "Tuvalu": "Australia / Oceania",
  "Uganda": "Africa",
  "Ukraine": "Europe",
  "United Arab Emirates": "Asia",
  "United Kingdom": "Europe",
  "United States": "North America",
  "Uruguay": "Central & South America",
  "Uzbekistan": "Asia",
  "Vanuatu": "Australia / Oceania",
  "Vatican City": "Europe",
  "Venezuela": "Central & South America",
  "Vietnam": "Asia",
  "Yemen": "Asia",
  "Zambia": "Africa",
  "Zimbabwe": "Africa",
};
