import { createClient } from '@/lib/supabase/server'
import { NextRequest, NextResponse } from 'next/server'

export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()

    if (!user) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      )
    }

    // Parse form data
    const formData = await request.formData()
    const file = formData.get('file') as File
    const title = formData.get('title') as string
    const description = formData.get('description') as string
    const organizationId = formData.get('organizationId') as string
    const visibilityLevel = formData.get('visibilityLevel') as string
    const publicationYear = formData.get('publicationYear') as string
    const researchType = formData.get('researchType') as string

    // Parse JSON fields
    const authors = formData.get('authors')
      ? JSON.parse(formData.get('authors') as string)
      : []
    const tags = formData.get('tags')
      ? JSON.parse(formData.get('tags') as string)
      : []
    const topics = formData.get('topics')
      ? JSON.parse(formData.get('topics') as string)
      : []

    // Validation
    if (!file || !title || !organizationId) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      )
    }

    // Verify user has contributor or admin role in the organization
    const { data: membership } = await supabase
      .from('organization_memberships')
      .select('role')
      .eq('user_id', user.id)
      .eq('organization_id', organizationId)
      .eq('is_active', true)
      .in('role', ['contributor', 'primary_admin', 'backup_admin'])
      .single()

    if (!membership) {
      return NextResponse.json(
        { error: 'You do not have permission to upload research for this organization' },
        { status: 403 }
      )
    }

    // Generate unique filename
    const timestamp = Date.now()
    const sanitizedFileName = file.name.replace(/[^a-zA-Z0-9.-]/g, '_')
    const uniqueFileName = `${organizationId}/${timestamp}_${sanitizedFileName}`

    // Upload to Supabase Storage
    const fileBuffer = await file.arrayBuffer()
    const { data: uploadData, error: uploadError } = await supabase.storage
      .from('research-documents')
      .upload(uniqueFileName, fileBuffer, {
        contentType: 'application/pdf',
        upsert: false,
      })

    if (uploadError) {
      console.error('Storage upload error:', uploadError)
      return NextResponse.json(
        { error: 'Failed to upload file to storage' },
        { status: 500 }
      )
    }

    // Get public URL for the file
    const { data: urlData } = supabase.storage
      .from('research-documents')
      .getPublicUrl(uniqueFileName)

    // Insert document record
    // Note: tsv (full-text search vector) is automatically generated by database trigger
    const { data: document, error: dbError } = await supabase
      .from('research_documents')
      .insert({
        organization_id: organizationId,
        uploaded_by_user_id: user.id,
        title,
        description: description || null,
        file_name: file.name,
        file_url: urlData.publicUrl,
        file_size_bytes: file.size,
        mime_type: 'application/pdf',
        publication_year: publicationYear ? parseInt(publicationYear) : null,
        authors,
        tags,
        topics,
        research_type: researchType || null,
        visibility_level: visibilityLevel,
      })
      .select('id')
      .single()

    if (dbError) {
      console.error('Database insert error:', dbError)
      // Clean up uploaded file
      await supabase.storage
        .from('research-documents')
        .remove([uniqueFileName])
      return NextResponse.json(
        { error: 'Failed to create document record' },
        { status: 500 }
      )
    }

    // Log activity
    await supabase.from('activity_logs').insert({
      user_id: user.id,
      organization_id: organizationId,
      action_type: 'research.uploaded',
      details: {
        document_id: document.id,
        title,
        file_name: file.name,
        visibility_level: visibilityLevel,
      },
    })

    return NextResponse.json({
      success: true,
      documentId: document.id,
    })
  } catch (error) {
    console.error('Research upload error:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}
